// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhP4xuGrUtYkVOF7oxiUYE60GVG-uuTXA',
    appId: '1:698361485208:web:33731ae55fbdfccb897ded',
    messagingSenderId: '698361485208',
    projectId: 'cepu-app-82578',
    authDomain: 'cepu-app-82578.firebaseapp.com',
    databaseURL: 'https://cepu-app-82578-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-82578.firebasestorage.app',
    measurementId: 'G-CBQPEWKWRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-QVp7oU7K13trLaLY61L8e4mQ6L_xzzc',
    appId: '1:698361485208:android:8f3f1d207d3264bc897ded',
    messagingSenderId: '698361485208',
    projectId: 'cepu-app-82578',
    databaseURL: 'https://cepu-app-82578-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-82578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2nfwMeo4431Ab0WGhFyYQ3a9qKwSDNdM',
    appId: '1:698361485208:ios:76a385a1728a8147897ded',
    messagingSenderId: '698361485208',
    projectId: 'cepu-app-82578',
    databaseURL: 'https://cepu-app-82578-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-82578.firebasestorage.app',
    iosClientId: '698361485208-3p7uabf98ribru6lof14eag7d1dhee19.apps.googleusercontent.com',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2nfwMeo4431Ab0WGhFyYQ3a9qKwSDNdM',
    appId: '1:698361485208:ios:76a385a1728a8147897ded',
    messagingSenderId: '698361485208',
    projectId: 'cepu-app-82578',
    databaseURL: 'https://cepu-app-82578-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-82578.firebasestorage.app',
    iosClientId: '698361485208-3p7uabf98ribru6lof14eag7d1dhee19.apps.googleusercontent.com',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhP4xuGrUtYkVOF7oxiUYE60GVG-uuTXA',
    appId: '1:698361485208:web:e0bb8f44b161ed81897ded',
    messagingSenderId: '698361485208',
    projectId: 'cepu-app-82578',
    authDomain: 'cepu-app-82578.firebaseapp.com',
    databaseURL: 'https://cepu-app-82578-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-82578.firebasestorage.app',
    measurementId: 'G-568KDBKM5T',
  );
}
