// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY6zmMfv1SKD0zKxPZw6VbcOIsBhM9ukE',
    appId: '1:684230198591:web:119087cf8705bf847ebf8a',
    messagingSenderId: '684230198591',
    projectId: 'notes-5a100',
    authDomain: 'notes-5a100.firebaseapp.com',
    storageBucket: 'notes-5a100.firebasestorage.app',
    measurementId: 'G-FJZNZZGMR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2JS98Jy4YQV3SuuWoaH0URyDvxgaH0Q',
    appId: '1:684230198591:android:7eb4c97f9d119cc37ebf8a',
    messagingSenderId: '684230198591',
    projectId: 'notes-5a100',
    storageBucket: 'notes-5a100.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP8-KioJC8LniQU11hTbB-zg_EgVXFFvw',
    appId: '1:684230198591:ios:b75f1055ba78032e7ebf8a',
    messagingSenderId: '684230198591',
    projectId: 'notes-5a100',
    storageBucket: 'notes-5a100.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8-KioJC8LniQU11hTbB-zg_EgVXFFvw',
    appId: '1:684230198591:ios:b75f1055ba78032e7ebf8a',
    messagingSenderId: '684230198591',
    projectId: 'notes-5a100',
    storageBucket: 'notes-5a100.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY6zmMfv1SKD0zKxPZw6VbcOIsBhM9ukE',
    appId: '1:684230198591:web:bdb285b01ecf1f0e7ebf8a',
    messagingSenderId: '684230198591',
    projectId: 'notes-5a100',
    authDomain: 'notes-5a100.firebaseapp.com',
    storageBucket: 'notes-5a100.firebasestorage.app',
    measurementId: 'G-F49QW4SQ3H',
  );

}